# Generated by Django 5.0.4 on 2024-07-26 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels_lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=50)),
                ('food_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='Food_image/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='hotels_lists.hotels')),
            ],
        ),
    ]
