# Generated by Django 5.0.4 on 2024-07-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='hotel',
        ),
    ]
